image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - yarn install
    - yarn build
#    - ./node_modules/lerna/cli.js bootstrap --use-workspaces
    - git fetch && git symbolic-ref -q HEAD > /dev/null || (git branch -d ${CI_COMMIT_REF_NAME} || true && git checkout -b ${CI_COMMIT_REF_NAME} && git branch --set-upstream-to=origin/${CI_COMMIT_REF_NAME} ${CI_COMMIT_REF_NAME})
    - ./node_modules/lerna/cli.js version --force-publish patch
