image: node:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - yarn install
    - yarn set version classic
    - ./node_modules/lerna/cli.js bootstrap --use-workspaces
    - ./node_modules/lerna/cli.js publish
