image: node:latest

stages:
  - deploy

deploy:
  variables:
    GL_TOKEN: $JEST_CI_TOKEN
  stage: deploy
  before_script:
    - git config --global user.email "bobalu@panterasbox.com"
    - git config --global user.name "Bobalu Smallberries"
  script:
    - git remote set-url origin https://${JEST_CI_USER}:${JEST_CI_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git/
    - git fetch && git symbolic-ref -q HEAD > /dev/null || (git branch -d ${CI_COMMIT_REF_NAME} || true && git checkout -b ${CI_COMMIT_REF_NAME} && git branch --set-upstream-to=origin/${CI_COMMIT_REF_NAME} ${CI_COMMIT_REF_NAME})
    - yarn install --immutable
    - yarn build
#    - ./node_modules/lerna/cli.js bootstrap --use-workspaces
    - ./node_modules/lerna/cli.js version --yes --conventional-commits --create-release gitlab
#    - ./node_modules/lerna/cli.js publish from-git
